# Generated by Django 5.0.2 on 2024-02-19 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('bed', models.IntegerField(default=0)),
                ('person', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoomsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.statusmodel')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.typesmodel')),
            ],
        ),
    ]
