# Generated by Django 5.0.2 on 2024-02-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
